"""tools/new.py — adding to a lab by copying the closest thing it has: a skill, a room, a role, a check, a
project type, a rule. Each test works on a throwaway copy of this lab's definition."""

from __future__ import annotations

import shutil

import pytest

from conftest import REPO, load


@pytest.fixture
def lab(tmp_path):
    hub = tmp_path / "hub"
    for rel in ("workflow", ".claude/skills", "agent-roles", "checks", "templates/project-types"):
        shutil.copytree(REPO / rel, hub / rel)
    (hub / "lab").mkdir()
    (hub / "AGENTS.md").write_text("## Hard rules\n\n" + "<!-- newts:hard-rules (generated by tools/workflow.py render-docs "
                                    "from workflow/) -->\n<!-- /newts:hard-rules -->\n", encoding="utf-8")
    return hub


@pytest.fixture
def new():
    return load("new")


def test_a_skill_like_another_inherits_its_definition_and_can_join_a_stage(lab, new):
    wf = load("workflow")
    new.new_skill(lab, "quick-scan", "lit-review", stage="literature", title="A quick literature scan")
    skill = (lab / ".claude" / "skills" / "quick-scan" / "SKILL.md").read_text(encoding="utf-8")
    assert "name: quick-scan" in skill and "like: lit-review" in skill and "brief quick-scan" in skill
    assert (lab / ".claude" / "skills" / "quick-scan" / "METHOD.md").exists()
    p, base = wf.procedure("quick-scan", lab), wf.procedure("lit-review", lab)
    assert p["title"] == "A quick literature scan" and p["level"] == base["level"] and p["outputs"] == base["outputs"]
    assert p["replaceable"] and "quick-scan" in wf.launch_registry(lab)
    assert any(st["id"] == "literature" and "quick-scan" in st["procedures"] for st in wf.load(lab)["stages"])
    assert not [x for x in wf.check(lab) if "quick-scan" in x]
    with pytest.raises(new.NewError):
        new.new_skill(lab, "quick-scan", "lit-review")


def test_a_room_like_another_takes_its_art_and_the_states_it_is_given(lab, new):
    wf = load("workflow")
    files = new.new_room(lab, "data", "lab", states=["analysis"], title="The Data Room")
    art = (lab / "lab" / "rooms" / "data.js").read_text(encoding="utf-8")
    key_line = next(ln for ln in art.splitlines() if "key:" in ln)
    assert "key: 'data'" in key_line and "order:" not in key_line      # its placement is the workflow's
    rooms = {r["id"]: r for r in wf.load(lab)["rooms"]}
    assert rooms["data"]["states"] == ["analysis"] and "analysis" not in rooms["lab"]["states"]
    assert rooms["data"]["floor"] == rooms["lab"]["floor"] and rooms["data"]["order"] == 4
    st = next(s for s in wf.load(lab)["states"] if s["id"] == "analysis")
    assert st["room"] == "data" and st["station"] in art
    assert wf.check(lab) == [] and files
    new.new_room(lab, "quiet", "margins", plain=True)
    assert not (lab / "lab" / "rooms" / "quiet.js").exists() and "quiet" in {r["id"] for r in wf.load(lab)["rooms"]}


def test_a_role_like_another_inherits_its_settings(lab, new, monkeypatch):
    new.new_role(lab, "data-wrangler", "experiment-runner", label="Data wrangler")
    rs = load("role_sync")
    monkeypatch.setattr(rs, "HUB", lab)
    assert rs.role_keys()["data-wrangler"] == rs.role_keys()["experiment-runner"]
    assert (lab / ".claude" / "agents" / "data-wrangler.md").exists()
    assert load("workflow").role_labels(lab)["data-wrangler"] == "Data wrangler"


def test_a_check_and_a_type_and_a_rule(lab, new):
    new.new_check(lab, "no-tabs", "writeback")
    assert 'NAME = "no-tabs"' in (lab / "checks" / "no_tabs.py").read_text(encoding="utf-8")
    new.new_type(lab, "survey", "empirical")
    assert load("labfiles").project_types(lab)["survey"].startswith("# Project type: `survey`")
    wf = load("workflow")
    new.new_rule(lab, "no-tabs", '**No tabs.** Indent with spaces: "always".', check="no-tabs")
    assert wf.check_rules(lab) == []
    wf.render_docs(lab)
    assert '14. **No tabs.** Indent with spaces: "always".' in (lab / "AGENTS.md").read_text(encoding="utf-8")


def test_names_are_checked(lab, new):
    for bad in ("Has Space", "x", "../up", "UPPER"):
        with pytest.raises(new.NewError):
            new.new_skill(lab, bad, "lit-review")
    with pytest.raises(new.NewError):
        new.new_room(lab, "data", "nope")
